version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sustainable_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis
    networks:
      - marketplace-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - marketplace-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - marketplace-network

networks:
  marketplace-network:
    driver: bridge

volumes:
  mongodb_data:
